"use client";

import styles from "./AIAnalysis.module.css";

interface AIAnalysisProps {
  analysis: string | null;
  loading: boolean;
  onGenerate: () => void;
  hasData: boolean;
}

/**
 * Very basic markdown-to-html: handles bold, headings, and line breaks.
 * Not a full parser — just enough for the structured AI output.
 */
function renderMarkdown(text: string): string {
  return text
    .split("\n")
    .map((line) => {
      // Headings
      if (line.startsWith("### ")) return `<h3>${line.slice(4)}</h3>`;
      if (line.startsWith("## ")) return `<h3>${line.slice(3)}</h3>`;
      if (line.startsWith("# ")) return `<h2>${line.slice(2)}</h2>`;
      // Horizontal rule
      if (line.match(/^-{3,}$/)) return "<hr />";
      // List items
      if (line.match(/^\s*[-*]\s/))
        return `<li>${line.replace(/^\s*[-*]\s/, "")}</li>`;
      if (line.match(/^\s*\d+\.\s/))
        return `<li>${line.replace(/^\s*\d+\.\s/, "")}</li>`;
      // Empty line
      if (line.trim() === "") return "";
      // Regular paragraph
      return `<p>${line}</p>`;
    })
    .join("")
    .replace(/<\/li><li>/g, "</li><li>")
    .replace(/(<li>)/g, (match, _p1, offset, str) => {
      // Wrap consecutive <li> blocks in <ul>
      if (offset === 0 || !str.substring(offset - 5, offset).includes("li>")) {
        return "<ul>" + match;
      }
      return match;
    })
    .replace(/<\/li>(?!<li>)/g, "</li></ul>")
    .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
}

export default function AIAnalysis({
  analysis,
  loading,
  onGenerate,
  hasData,
}: AIAnalysisProps) {
  if (!analysis && !loading) {
    return (
      <div className={styles.card} id="ai-analysis">
        <h3 className={styles.title}>AI Analysis</h3>
        <button
          className={styles.generateButton}
          onClick={onGenerate}
          disabled={!hasData}
          id="generate-analysis-button"
        >
          {hasData
            ? "Generate AI Investment Analysis"
            : "Search a stock first to generate analysis"}
        </button>
      </div>
    );
  }

  if (loading) {
    return (
      <div className={styles.card} id="ai-analysis">
        <h3 className={styles.title}>AI Analysis</h3>
        <div className={styles.loading}>
          <div className={styles.spinner} />
          Generating analysis with Grok...
        </div>
      </div>
    );
  }

  return (
    <div className={styles.card} id="ai-analysis">
      <div className={styles.header}>
        <h3 className={styles.title}>AI Analysis</h3>
        <span className={styles.badge}>Powered by Grok</span>
      </div>
      <div
        className={styles.content}
        dangerouslySetInnerHTML={{ __html: renderMarkdown(analysis || "") }}
      />
      <div className={styles.disclaimer}>
        This analysis is generated by AI for informational purposes only. It
        does not constitute financial advice. Always do your own research before
        making investment decisions.
      </div>
    </div>
  );
}
